receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        tls:
          cert_file: /etc/otel/certs/otel-server.crt
          key_file: /etc/otel/certs/otel-server.key
          client_ca_file: /etc/otel/certs/ca.crt
          client_ca_file_reload: true
          require_client_auth: true
      http:
        endpoint: 0.0.0.0:4318
        tls:
          cert_file: /etc/otel/certs/otel-server.crt
          key_file: /etc/otel/certs/otel-server.key
          client_ca_file: /etc/otel/certs/ca.crt
          client_ca_file_reload: true
          require_client_auth: true

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024

  memory_limiter:
    check_interval: 1s
    limit_mib: 512

  resource:
    attributes:
      - key: service.environment
        value: development
        action: insert

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: mentishub

  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  otlphttp/loki:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [otlp/tempo, debug]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [prometheus, debug]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [otlphttp/loki, debug]

  telemetry:
    logs:
      level: info
